[spad]
language = "SPAD"
version = "5.0.0"

[repos]
sources = ["packages-local"]
local_sources = ["packages-local"]

[packages]
sets = ["T", "S", "P", "A", "D", "L"]

[extensions]
languages = ["spad", "java", "lua"]
